// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/deductions/{type}": {
            "post": {
                "description": "Change deduction from request based on the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "Change deduction from request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type of deduction: personal or k-receipt",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Amount to be deducted",
                        "name": "amount",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns the updated deduction",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "number"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax.Err"
                        }
                    }
                }
            }
        },
        "/tax/calculations": {
            "post": {
                "description": "Calculate tax from request based on the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "Calculate tax from request",
                "parameters": [
                    {
                        "description": "Tax data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tax.TaxRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns the tax calculation",
                        "schema": {
                            "$ref": "#/definitions/tax.TaxResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax.Err"
                        }
                    }
                }
            }
        },
        "/tax/calculations/upload-csv": {
            "post": {
                "description": "Calculate tax based on the data provided in a CSV file",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "tax"
                ],
                "summary": "Calculate tax from CSV file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file containing tax data",
                        "name": "taxFile",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the calculated tax",
                        "schema": {
                            "$ref": "#/definitions/tax.TaxCSVResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax.Err"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "tax.Allowance": {
            "type": "object",
            "properties": {
                "allowanceType": {
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                }
            }
        },
        "tax.Err": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "tax.TaxCSVResponse": {
            "type": "object",
            "properties": {
                "taxes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tax.TaxCSVResponseDetail"
                    }
                }
            }
        },
        "tax.TaxCSVResponseDetail": {
            "type": "object",
            "properties": {
                "tax": {
                    "type": "number"
                },
                "taxRefund": {
                    "type": "number"
                },
                "totalIncome": {
                    "type": "number"
                }
            }
        },
        "tax.TaxLevel": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "tax": {
                    "type": "number"
                },
                "taxRefund": {
                    "type": "number"
                }
            }
        },
        "tax.TaxRequest": {
            "type": "object",
            "properties": {
                "allowances": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tax.Allowance"
                    }
                },
                "totalIncome": {
                    "type": "number"
                },
                "wht": {
                    "type": "number"
                }
            }
        },
        "tax.TaxResponse": {
            "type": "object",
            "properties": {
                "tax": {
                    "type": "number"
                },
                "taxLevel": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tax.TaxLevel"
                    }
                },
                "taxRefund": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
