# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: go mod download

    - name: Start Server
      run: go run main.go &

    - name: Wait for Server to Start
      run: sleep 5

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...

    - name: Run static code analysis
      run: go vet ./...

    - name: Format code
      run: go fmt ./...

    - name: Build Docker Image
      run: |
        docker build -t my-go-app .